version: '3'

networks:
  rss-feed-network:

services:

#  postgres:
#    image: "postgres:latest"
#    container_name: "postgres"
#    environment:
#      - POSTGRES_PASSWORD=password
#      - POSTGRES_USER=postgres
#      - POSTGRES_DB=mydb
#    ports:
#      - "5432:5432"
#    volumes:
#      - "$HOME/docker/volumes/postgres:/var/lib/postgresql/data"
#    networks:
#      rss-feed-network:
#        aliases:
#          - server

  server:
    image: "rss-server"
    container_name: "server"
    build: .
#    environment:
#      - POSTGRES_PASSWORD=password
#      - POSTGRES_USER=postgres
#      - POSTGRES_DB=mydb
#    depends_on:
#      - postgres
#    networks:
#      rss-feed-network:
#        aliases:
#          - postgres
    ports:
      - 80:8080